// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSchool.Models;

#nullable disable

namespace eSchool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805045149_AddLoaiTinToTinTucSuKien")]
    partial class AddLoaiTinToTinTucSuKien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HocSinh", b =>
                {
                    b.Property<int>("IdHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocSinh"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DanToc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdLopHoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaHS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayNhapHoc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiSinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuocTich")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TonGiao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHocSinh");

                    b.HasIndex("IdLopHoc");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique()
                        .HasFilter("[IdTaiKhoan] IS NOT NULL");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("eSchool.Models.BaoTri", b =>
                {
                    b.Property<int>("IdBaoTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBaoTri"));

                    b.Property<decimal>("ChiPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IdThietBi")
                        .HasColumnType("int");

                    b.Property<string>("KetQua")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaBaoTri")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayBaoTri")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiThucHien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdBaoTri");

                    b.HasIndex("IdThietBi");

                    b.ToTable("BaoTris");
                });

            modelBuilder.Entity("eSchool.Models.ChinhSachMienGiam", b =>
                {
                    b.Property<int>("IdMienGiam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMienGiam"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HieuLuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("PhanTramGiam")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("IdMienGiam");

                    b.HasIndex("IdHocSinh");

                    b.ToTable("ChinhSachMienGiams");
                });

            modelBuilder.Entity("eSchool.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("eSchool.Models.ChuyenLop", b =>
                {
                    b.Property<int>("IdChuyenLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChuyenLop"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLopCu")
                        .HasColumnType("int");

                    b.Property<int>("IdLopMoi")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayChuyen")
                        .HasColumnType("datetime2");

                    b.HasKey("IdChuyenLop");

                    b.HasIndex("IdHocSinh");

                    b.ToTable("ChuyenLops");
                });

            modelBuilder.Entity("eSchool.Models.DangKyLop", b =>
                {
                    b.Property<int>("IdDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDangKy"));

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDangKy");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdLop");

                    b.ToTable("DangKyLops");
                });

            modelBuilder.Entity("eSchool.Models.Diem", b =>
                {
                    b.Property<int>("IdDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiem"));

                    b.Property<string>("Diem15Phut")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Diem1Tiet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiemCuoiKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiemGiuaKy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("DiemTB")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdHocKy")
                        .HasColumnType("int");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdNamHoc")
                        .HasColumnType("int");

                    b.HasKey("IdDiem");

                    b.HasIndex("IdHocKy");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdNamHoc");

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("eSchool.Models.DiemDanh", b =>
                {
                    b.Property<int>("IdDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiemDanh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<int?>("IdTietHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdDiemDanh");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdLop");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.Property<int>("IdGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiaoVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdGiaoVien");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique()
                        .HasFilter("[IdTaiKhoan] IS NOT NULL");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("eSchool.Models.HocKy", b =>
                {
                    b.Property<int>("IdHocKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocKy"));

                    b.Property<int>("IdNamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenHocKy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHocKy");

                    b.HasIndex("IdNamHoc");

                    b.ToTable("HocKys");
                });

            modelBuilder.Entity("eSchool.Models.HocPhi", b =>
                {
                    b.Property<int>("IdHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocPhi"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("HanDongTien")
                        .HasColumnType("datetime2");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdHocKy")
                        .HasColumnType("int");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdNamHoc")
                        .HasColumnType("int");

                    b.Property<string>("LyDoMienGiam")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDuKien")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PhanTramMienGiam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("SoTienMienGiam")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdHocPhi");

                    b.HasIndex("IdHocKy");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdNamHoc");

                    b.ToTable("HocPhis");
                });

            modelBuilder.Entity("eSchool.Models.HocSinhPhuHuynh", b =>
                {
                    b.Property<int>("IdHocSinhPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocSinhPhuHuynh"));

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdPhuHuynh")
                        .HasColumnType("int");

                    b.Property<bool>("LaLienHeChinh")
                        .HasColumnType("bit");

                    b.Property<string>("QuanHe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdHocSinhPhuHuynh");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdPhuHuynh");

                    b.ToTable("HocSinhPhuHuynhs");
                });

            modelBuilder.Entity("eSchool.Models.KyLuat", b =>
                {
                    b.Property<int>("IdKyLuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdKyLuat"));

                    b.Property<string>("HinhThuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<int?>("IdHocKy")
                        .HasColumnType("int");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("NgayViPham")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdKyLuat");

                    b.HasIndex("IdGiaoVien");

                    b.HasIndex("IdHocKy");

                    b.HasIndex("IdHocSinh");

                    b.ToTable("KyLuats");
                });

            modelBuilder.Entity("eSchool.Models.LichHocThayDoi", b =>
                {
                    b.Property<int>("IdThayDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThayDoi"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("IdGiaoVienThayThe")
                        .HasColumnType("int");

                    b.Property<int?>("IdLop")
                        .HasColumnType("int");

                    b.Property<int?>("IdMonHocThayThe")
                        .HasColumnType("int");

                    b.Property<bool>("IsNghi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoTiet")
                        .HasColumnType("int");

                    b.Property<int?>("TietBatDau")
                        .HasColumnType("int");

                    b.HasKey("IdThayDoi");

                    b.HasIndex("IdGiaoVienThayThe");

                    b.HasIndex("IdLop");

                    b.HasIndex("IdMonHocThayThe");

                    b.ToTable("LichHocThayDois");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.Property<int>("IdLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLop"));

                    b.Property<string>("BuoiHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdGiaoVienCN")
                        .HasColumnType("int");

                    b.Property<string>("Khoi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLop");

                    b.HasIndex("IdGiaoVienCN");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("eSchool.Models.MonHoc", b =>
                {
                    b.Property<int>("IdMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonHoc"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMonHoc");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("eSchool.Models.NamHoc", b =>
                {
                    b.Property<int>("IdNamHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNamHoc"));

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenNamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdNamHoc");

                    b.ToTable("NamHocs");
                });

            modelBuilder.Entity("eSchool.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("IdNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhatKy"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("IdNhatKy");

                    b.ToTable("NhatKyHoatDongs");
                });

            modelBuilder.Entity("eSchool.Models.PhanCongGiangDay", b =>
                {
                    b.Property<int>("IdPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhanCong"));

                    b.Property<string>("HocKy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<int>("IdMonHoc")
                        .HasColumnType("int");

                    b.Property<int?>("IdPhongHoc")
                        .HasColumnType("int");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("SoTiet")
                        .HasColumnType("int");

                    b.Property<int?>("Thu")
                        .HasColumnType("int");

                    b.Property<int?>("TietBatDau")
                        .HasColumnType("int");

                    b.HasKey("IdPhanCong");

                    b.HasIndex("IdGiaoVien");

                    b.HasIndex("IdLop");

                    b.HasIndex("IdMonHoc");

                    b.HasIndex("IdPhongHoc");

                    b.ToTable("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.PhieuDiem", b =>
                {
                    b.Property<int>("IdPhieuDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhieuDiem"));

                    b.Property<int?>("IdHocKy")
                        .HasColumnType("int");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int?>("IdLop")
                        .HasColumnType("int");

                    b.Property<int?>("IdNamHoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiLap")
                        .HasColumnType("int");

                    b.HasKey("IdPhieuDiem");

                    b.HasIndex("IdHocKy");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdLop");

                    b.HasIndex("IdNamHoc");

                    b.HasIndex("NguoiLap");

                    b.ToTable("PhieuDiems");
                });

            modelBuilder.Entity("eSchool.Models.PhongHoc", b =>
                {
                    b.Property<int>("IdPhongHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhongHoc"));

                    b.Property<int?>("IdLop")
                        .HasColumnType("int");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhong")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("TrangThietBi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdPhongHoc");

                    b.HasIndex("IdLop");

                    b.ToTable("PhongHocs");
                });

            modelBuilder.Entity("eSchool.Models.PhuHuynh", b =>
                {
                    b.Property<int>("IdPhuHuynh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhuHuynh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NgheNghiep")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdPhuHuynh");

                    b.ToTable("PhuHuynhs");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<bool>("BatBuocDoiMatKhau")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdChucVu");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("eSchool.Models.ThietBi", b =>
                {
                    b.Property<int>("IdThietBi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThietBi"));

                    b.Property<int>("IdPhongHoc")
                        .HasColumnType("int");

                    b.Property<string>("LoaiTB")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTB")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenTB")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdThietBi");

                    b.HasIndex("IdPhongHoc");

                    b.ToTable("ThietBis");
                });

            modelBuilder.Entity("eSchool.Models.ThongBao", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"));

                    b.Property<int>("DoiTuongNhan")
                        .HasColumnType("int");

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("eSchool.Models.TinTucSuKien", b =>
                {
                    b.Property<int>("IdTinTucSuKien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTinTucSuKien"));

                    b.Property<string>("AnhMinhHoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LoaiTin")
                        .HasColumnType("int");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ThoiGianDoc")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdTinTucSuKien");

                    b.ToTable("TinTucSuKiens");
                });

            modelBuilder.Entity("HocSinh", b =>
                {
                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("IdLopHoc");

                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocSinh")
                        .HasForeignKey("HocSinh", "IdTaiKhoan");

                    b.Navigation("LopHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("eSchool.Models.BaoTri", b =>
                {
                    b.HasOne("eSchool.Models.ThietBi", "ThietBi")
                        .WithMany()
                        .HasForeignKey("IdThietBi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThietBi");
                });

            modelBuilder.Entity("eSchool.Models.ChinhSachMienGiam", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("eSchool.Models.ChuyenLop", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("ChuyenLops")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("eSchool.Models.DangKyLop", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("DangKyLops")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("DangKyLops")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("eSchool.Models.Diem", b =>
                {
                    b.HasOne("eSchool.Models.HocKy", "HocKyInfo")
                        .WithMany("Diems")
                        .HasForeignKey("IdHocKy");

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("Diems")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.MonHoc", "MonHoc")
                        .WithMany("Diems")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.NamHoc", "NamHocInfo")
                        .WithMany("Diems")
                        .HasForeignKey("IdNamHoc");

                    b.Navigation("HocKyInfo");

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");

                    b.Navigation("NamHocInfo");
                });

            modelBuilder.Entity("eSchool.Models.DiemDanh", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.HasOne("eSchool.Models.MonHoc", "MonHoc")
                        .WithMany("GiaoViens")
                        .HasForeignKey("IdMonHoc");

                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiaoVien")
                        .HasForeignKey("eSchool.Models.GiaoVien", "IdTaiKhoan");

                    b.Navigation("MonHoc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("eSchool.Models.HocKy", b =>
                {
                    b.HasOne("eSchool.Models.NamHoc", "NamHoc")
                        .WithMany("HocKys")
                        .HasForeignKey("IdNamHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("eSchool.Models.HocPhi", b =>
                {
                    b.HasOne("eSchool.Models.HocKy", "HocKyInfo")
                        .WithMany("HocPhis")
                        .HasForeignKey("IdHocKy");

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("HocPhis")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.NamHoc", "NamHoc")
                        .WithMany("HocPhis")
                        .HasForeignKey("IdNamHoc");

                    b.Navigation("HocKyInfo");

                    b.Navigation("HocSinh");

                    b.Navigation("NamHoc");
                });

            modelBuilder.Entity("eSchool.Models.HocSinhPhuHuynh", b =>
                {
                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("HocSinhPhuHuynhs")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.PhuHuynh", "PhuHuynh")
                        .WithMany("HocSinhPhuHuynhs")
                        .HasForeignKey("IdPhuHuynh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("PhuHuynh");
                });

            modelBuilder.Entity("eSchool.Models.KyLuat", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("IdGiaoVien");

                    b.HasOne("eSchool.Models.HocKy", "HocKyInfo")
                        .WithMany()
                        .HasForeignKey("IdHocKy");

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany()
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("HocKyInfo");

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("eSchool.Models.LichHocThayDoi", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVienThayThe")
                        .WithMany()
                        .HasForeignKey("IdGiaoVienThayThe");

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("IdLop");

                    b.HasOne("eSchool.Models.MonHoc", "MonHocThayThe")
                        .WithMany()
                        .HasForeignKey("IdMonHocThayThe");

                    b.Navigation("GiaoVienThayThe");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHocThayThe");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVienChuNhiem")
                        .WithMany("LopChuNhiems")
                        .HasForeignKey("IdGiaoVienCN");

                    b.Navigation("GiaoVienChuNhiem");
                });

            modelBuilder.Entity("eSchool.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdGiaoVien");

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.MonHoc", "MonHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("IdPhongHoc");

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("eSchool.Models.PhieuDiem", b =>
                {
                    b.HasOne("eSchool.Models.HocKy", "HocKy")
                        .WithMany("PhieuDiems")
                        .HasForeignKey("IdHocKy");

                    b.HasOne("HocSinh", "HocSinh")
                        .WithMany("PhieuDiems")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("PhieuDiems")
                        .HasForeignKey("IdLop");

                    b.HasOne("eSchool.Models.NamHoc", "NamHoc")
                        .WithMany("PhieuDiems")
                        .HasForeignKey("IdNamHoc");

                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoanNguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLap");

                    b.Navigation("HocKy");

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");

                    b.Navigation("NamHoc");

                    b.Navigation("TaiKhoanNguoiLap");
                });

            modelBuilder.Entity("eSchool.Models.PhongHoc", b =>
                {
                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany()
                        .HasForeignKey("IdLop");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.HasOne("eSchool.Models.ChucVu", "ChucVu")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("eSchool.Models.ThietBi", b =>
                {
                    b.HasOne("eSchool.Models.PhongHoc", "PhongHoc")
                        .WithMany()
                        .HasForeignKey("IdPhongHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("eSchool.Models.ThongBao", b =>
                {
                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("HocSinh", b =>
                {
                    b.Navigation("ChuyenLops");

                    b.Navigation("DangKyLops");

                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");

                    b.Navigation("HocPhis");

                    b.Navigation("HocSinhPhuHuynhs");

                    b.Navigation("PhieuDiems");
                });

            modelBuilder.Entity("eSchool.Models.ChucVu", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.Navigation("LopChuNhiems");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.HocKy", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("HocPhis");

                    b.Navigation("PhieuDiems");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.Navigation("DangKyLops");

                    b.Navigation("DiemDanhs");

                    b.Navigation("PhanCongGiangDays");

                    b.Navigation("PhieuDiems");
                });

            modelBuilder.Entity("eSchool.Models.MonHoc", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("GiaoViens");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.NamHoc", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("HocKys");

                    b.Navigation("HocPhis");

                    b.Navigation("PhieuDiems");
                });

            modelBuilder.Entity("eSchool.Models.PhuHuynh", b =>
                {
                    b.Navigation("HocSinhPhuHuynhs");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
