// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSchool.Models;

#nullable disable

namespace eSchool.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612181125_AddNhatKyHoatDong")]
    partial class AddNhatKyHoatDong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eSchool.Models.ChucVu", b =>
                {
                    b.Property<int>("IdChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChucVu"));

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdChucVu");

                    b.ToTable("ChucVus");
                });

            modelBuilder.Entity("eSchool.Models.DangKyLop", b =>
                {
                    b.Property<int>("IdDangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDangKy"));

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDangKy");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdLop");

                    b.ToTable("DangKyLops");
                });

            modelBuilder.Entity("eSchool.Models.Diem", b =>
                {
                    b.Property<int>("IdDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiem"));

                    b.Property<double?>("Diem15Phut")
                        .HasColumnType("float");

                    b.Property<double?>("Diem1Tiet")
                        .HasColumnType("float");

                    b.Property<double?>("DiemMieng")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThi")
                        .HasColumnType("float");

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdMonHoc")
                        .HasColumnType("int");

                    b.HasKey("IdDiem");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdMonHoc");

                    b.ToTable("Diems");
                });

            modelBuilder.Entity("eSchool.Models.DiemDanh", b =>
                {
                    b.Property<int>("IdDiemDanh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiemDanh"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayHoc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdDiemDanh");

                    b.HasIndex("IdHocSinh");

                    b.HasIndex("IdLop");

                    b.ToTable("DiemDanhs");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.Property<int>("IdGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGiaoVien"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaGV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("IdGiaoVien");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique()
                        .HasFilter("[IdTaiKhoan] IS NOT NULL");

                    b.ToTable("GiaoViens");
                });

            modelBuilder.Entity("eSchool.Models.HocPhi", b =>
                {
                    b.Property<int>("IdHocPhi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocPhi"));

                    b.Property<string>("HocKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDong")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdHocPhi");

                    b.HasIndex("IdHocSinh");

                    b.ToTable("HocPhis");
                });

            modelBuilder.Entity("eSchool.Models.HocSinh", b =>
                {
                    b.Property<int>("IdHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHocSinh"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MaHS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("IdHocSinh");

                    b.HasIndex("IdTaiKhoan")
                        .IsUnique()
                        .HasFilter("[IdTaiKhoan] IS NOT NULL");

                    b.ToTable("HocSinhs");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.Property<int>("IdLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLop"));

                    b.Property<int?>("IdGiaoVienCN")
                        .HasColumnType("int");

                    b.Property<string>("Khoi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdLop");

                    b.HasIndex("IdGiaoVienCN");

                    b.ToTable("LopHocs");
                });

            modelBuilder.Entity("eSchool.Models.MonHoc", b =>
                {
                    b.Property<int>("IdMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMonHoc"));

                    b.Property<string>("MaMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdMonHoc");

                    b.ToTable("MonHocs");
                });

            modelBuilder.Entity("eSchool.Models.NhatKyHoatDong", b =>
                {
                    b.Property<int>("IdNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNhatKy"));

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("IdNhatKy");

                    b.ToTable("NhatKyHoatDongs");
                });

            modelBuilder.Entity("eSchool.Models.PhanCongGiangDay", b =>
                {
                    b.Property<int>("IdPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPhanCong"));

                    b.Property<string>("HocKy")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdGiaoVien")
                        .HasColumnType("int");

                    b.Property<int>("IdLop")
                        .HasColumnType("int");

                    b.Property<int>("IdMonHoc")
                        .HasColumnType("int");

                    b.Property<string>("NamHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPhanCong");

                    b.HasIndex("IdGiaoVien");

                    b.HasIndex("IdLop");

                    b.HasIndex("IdMonHoc");

                    b.ToTable("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.Property<int>("IdTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTaiKhoan"));

                    b.Property<int>("IdChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTaiKhoan");

                    b.HasIndex("IdChucVu");

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("eSchool.Models.ThongBao", b =>
                {
                    b.Property<int>("IdThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdThongBao"));

                    b.Property<int>("IdTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdThongBao");

                    b.HasIndex("IdTaiKhoan");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("eSchool.Models.DangKyLop", b =>
                {
                    b.HasOne("eSchool.Models.HocSinh", "HocSinh")
                        .WithMany("DangKyLops")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("DangKyLops")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("eSchool.Models.Diem", b =>
                {
                    b.HasOne("eSchool.Models.HocSinh", "HocSinh")
                        .WithMany("Diems")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.MonHoc", "MonHoc")
                        .WithMany("Diems")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("eSchool.Models.DiemDanh", b =>
                {
                    b.HasOne("eSchool.Models.HocSinh", "HocSinh")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("DiemDanhs")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("GiaoVien")
                        .HasForeignKey("eSchool.Models.GiaoVien", "IdTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("eSchool.Models.HocPhi", b =>
                {
                    b.HasOne("eSchool.Models.HocSinh", "HocSinh")
                        .WithMany("HocPhis")
                        .HasForeignKey("IdHocSinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocSinh");
                });

            modelBuilder.Entity("eSchool.Models.HocSinh", b =>
                {
                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("HocSinh")
                        .HasForeignKey("eSchool.Models.HocSinh", "IdTaiKhoan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVienChuNhiem")
                        .WithMany("LopChuNhiems")
                        .HasForeignKey("IdGiaoVienCN");

                    b.Navigation("GiaoVienChuNhiem");
                });

            modelBuilder.Entity("eSchool.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("eSchool.Models.GiaoVien", "GiaoVien")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdGiaoVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eSchool.Models.MonHoc", "MonHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("IdMonHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.HasOne("eSchool.Models.ChucVu", "ChucVu")
                        .WithMany("TaiKhoans")
                        .HasForeignKey("IdChucVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChucVu");
                });

            modelBuilder.Entity("eSchool.Models.ThongBao", b =>
                {
                    b.HasOne("eSchool.Models.TaiKhoan", "TaiKhoan")
                        .WithMany("ThongBaos")
                        .HasForeignKey("IdTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("eSchool.Models.ChucVu", b =>
                {
                    b.Navigation("TaiKhoans");
                });

            modelBuilder.Entity("eSchool.Models.GiaoVien", b =>
                {
                    b.Navigation("LopChuNhiems");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.HocSinh", b =>
                {
                    b.Navigation("DangKyLops");

                    b.Navigation("DiemDanhs");

                    b.Navigation("Diems");

                    b.Navigation("HocPhis");
                });

            modelBuilder.Entity("eSchool.Models.LopHoc", b =>
                {
                    b.Navigation("DangKyLops");

                    b.Navigation("DiemDanhs");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.MonHoc", b =>
                {
                    b.Navigation("Diems");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("eSchool.Models.TaiKhoan", b =>
                {
                    b.Navigation("GiaoVien");

                    b.Navigation("HocSinh");

                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
